[package]
name = "cnu-bachelor-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["ShapeLayer"]
description = "Bachelor's thesis template for Chonnam National University."
repository = "https://github.com/ShapeLayer/bachelor-thesis-template-cnu-ce"
keywords = ["thesis", "korean", "chonnam"]
categories = ["template"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
